spring: 
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: maple8542!
    url: 'jdbc:mysql://springshoppingmall.cptnit8lonn3.ap-northeast-2.rds.amazonaws.com:3306/shopdb?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false     '
    username: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
graphql:
  spqr:
    gui:
      enabled: true
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true

server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-15-165-93-6.ap-northeast-2.compute.amazonaws.com:8080/eureka/ 
    healthcheck:
      enabled: true
